[package]
name = "wrds"
version = "0.0.1"
edition = "2021"
license = "MIT OR Apache 2.0"

[features]
default = []
heapless = ["dep:heapless"]
fuzzing = ["dep:arbitrary"]

[dependencies]
heapless = { version = "0.9", optional = true }
arbitrary = { version = "1", features = ["derive"], optional = true }
