[package]
name = "wrds"
version = "0.0.1"
edition = "2021"
license = "MIT OR Apache 2.0"

[features]
fuzzing = ["dep:arbitrary"]

[dependencies]
heapless = "0.9"
arbitrary = { version = "1", features = ["derive"], optional = true }
